### ISSUE TITLE
Disable middleware when ALLOWED_HOSTS is set to '*'?

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/django-allow-cidr#2]
The current behavior will check IP ranges even if ALLOWED_HOSTS is set to allow everything which feels counter-intuitive. Maybe we should deactivate the middleware when `ALLOWED_HOSTS='*'` since django allows everything to pass?

**Comment by pmac** [comment]
Yes! Great point. I had that as a feature at the beginning and then changed. Since the middleware changes the ALLOWED_HOSTS setting itself it's hard to tell if it's set to `['*']` originally or this is just another instance of the middleware class. So I think I'll check to see if the ORIG_ALLOWED_HOSTS variable is also empty. I'll have a PR shortly.

**Comment by pmac** [comment]
Fixed in 5d3e2cb76b58faf15a9b7df45395428d342e4586.

**Comment by pmac** [comment]
Released in `v0.3.0`.
